// Code generated by protoc-gen-go.
// source: input/message.proto
// DO NOT EDIT!

/*
Package tutorial is a generated protocol buffer package.

It is generated from these files:
	input/message.proto

It has these top-level messages:
	Person
	AddressBook
*/
package tutorial

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// reserved 2, 15, 9 to 11;
type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Query            *string `protobuf:"bytes,1,req,name=query" json:"query,omitempty"`
	PageNumber       *int32  `protobuf:"varint,2,opt,name=page_number" json:"page_number,omitempty"`
	ResultPerPage    *int32  `protobuf:"varint,3,req,name=result_per_page" json:"result_per_page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *Person) GetPageNumber() int32 {
	if m != nil && m.PageNumber != nil {
		return *m.PageNumber
	}
	return 0
}

func (m *Person) GetResultPerPage() int32 {
	if m != nil && m.ResultPerPage != nil {
		return *m.ResultPerPage
	}
	return 0
}

// Our address book file is just one of these.
type AddressBook struct {
	People           []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "tutorial.Person")
	proto.RegisterType((*AddressBook)(nil), "tutorial.AddressBook")
	proto.RegisterEnum("tutorial.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0x8e, 0xcf, 0x4a, 0x85, 0x40,
	0x14, 0xc6, 0xd3, 0x9b, 0x72, 0xef, 0x91, 0x68, 0x98, 0xbb, 0xc8, 0xa5, 0xb8, 0x12, 0x02, 0x85,
	0xde, 0x20, 0x41, 0x28, 0x4a, 0x94, 0x08, 0x5a, 0x8a, 0xe1, 0xa1, 0x24, 0x9d, 0x33, 0x9d, 0x99,
	0x59, 0xf8, 0xf6, 0x8d, 0xc4, 0xdd, 0x7d, 0xf0, 0xfd, 0xfb, 0xc1, 0x79, 0x56, 0xda, 0xd9, 0x6a,
	0x45, 0x63, 0xc6, 0x2f, 0x2c, 0x35, 0x93, 0x25, 0x79, 0xb4, 0xce, 0x12, 0xcf, 0xe3, 0x92, 0x33,
	0xc4, 0x3d, 0xb2, 0x21, 0x25, 0x6f, 0x20, 0xfa, 0x75, 0xc8, 0x5b, 0x1a, 0x64, 0x61, 0x71, 0x92,
	0x67, 0x48, 0xb4, 0x2f, 0x0c, 0xca, 0xad, 0x9f, 0xc8, 0x69, 0x98, 0x05, 0x45, 0x24, 0xef, 0xe0,
	0x96, 0xd1, 0xb8, 0xc5, 0x0e, 0x1a, 0x79, 0xd8, 0xfd, 0xf4, 0xe0, 0xd3, 0x51, 0x7e, 0x0f, 0xa7,
	0xfe, 0x9b, 0x14, 0xbe, 0x6f, 0x1a, 0x25, 0x40, 0xdc, 0x76, 0xf5, 0xf3, 0x6b, 0x23, 0xae, 0xe4,
	0x11, 0xae, 0x9f, 0xba, 0xb6, 0x11, 0xc1, 0xae, 0x3e, 0xba, 0xb7, 0x17, 0x11, 0xe6, 0x15, 0x24,
	0x8f, 0xd3, 0xe4, 0x87, 0x4c, 0x4d, 0xf4, 0x23, 0x33, 0x88, 0x35, 0x92, 0x5e, 0xd0, 0x3f, 0x1f,
	0x8a, 0xe4, 0x41, 0x94, 0x17, 0xba, 0xf2, 0x1f, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xd8,
	0x0e, 0x7c, 0xc4, 0x00, 0x00, 0x00,
}
